### ISSUE TITLE
Finalizing hardware requirements & getting hardware

### ISSUE THREAD

**Issue by mikeshams** [Surjeet-1995/capstone-project-summer-2020#1]

**Comment by Surjeet-1995** [comment]
the hardware we are using in this project are -
1. **_Ada fruit 4 digit 7 segment display with i2c backpack_** this display has i2c interface facility and low cost. we can save much pins on beagle bone as compared to the non i2c interface.we don't need character display because we are only going to show the number (digits) of letters. we can show up to 4 digits in this display.
2. **_Ada fruit WiFi USB adapter_** this WI-fi adapter support the 802.11b/g/n protocol and has auto switching capability. the antenna is in-built in adapter motherboard and does not required external power supply. its small size and easy USB interface makes it good choice for our project.
3. **_Ada fruit FONA 800 GSM module_** this module supports the canadian  band frequency 850/1900mhz. it support every sim card.
4. **_Beagle Bone Black_**  this small has inbuilt adc, dac converters ,support pwm and gpio pins. the two headers on board provides different interface like i2c,uart also has usb and ethernet. it is not limited to any one programming language, we can run python, c, java in beagle bone. it is small in size and low -cost requires only 5 volts to operate.
5. **_HC SR04 Sensors_** the ultrasonic sensors are used in our project as it works great in dark area. its accuracy is good in dark area as compare to infared sensors
