### ISSUE TITLE
Interfacing of Wi-fi, Cloud service and ultrasonic sensors with beagle bone.

### ISSUE THREAD

**Issue by mikeshams** [Surjeet-1995/capstone-project-summer-2020#3]

**Comment by Surjeet-1995** [comment]
i have interfaced the wi-fi, ultrasonic sensor with beagle bone. the code i wrote is unique because there is no such help of beagle bone and c language for ultrasonic sensors. so i took references from python language and write  the code in c language. the cloud service is also included in this task. now i am able to ping data stored in Microcontroller from sensors to ThingSpeak cloud service.
i have uploaded the c code on github and presentation file on moodle

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of an ultrasonic sensor to a BBB in terms of Hardware and software?
2. Did you use dbt files? why not?
3. What issues did you or others might face with connection to WiFi in terms of Hardware and software?

**Comment by Surjeet-1995** [comment]
answer 1 : in term of software we need the libraries for ultrasonic sensors if we are using c or any other language. in coding we must define the p header of beagle bone and pin number. if we are working with c language then we don't have much libraries for ultrasonic sensors. to use the gpio pins and required delay in between the trig the iolib header file must be there. and in case of hardware the only difficulty we can face  is the powering the sensors. beagle bone has vdd5v and sys5v supply on its header. if we are powering beagle bone with power adapter (not using usb from pc) then sensors should be connected on vdd5v otherwise if we are using pc to power beagle bone then sensor should get supply from sys5v pin 7 on p9 header.

**Comment by Surjeet-1995** [comment]
answer 2: no we did not have used dbt file because this file belongs to database and in this project we don't need to use data base

**Comment by Surjeet-1995** [comment]
answer 3: i have not faced much issue while interfacing the wifi module. we are using the USB wifi adapter , just plug and use it. in software the official website of beaglebone has some tutorials to turn on the wifi of beagle bone black. the only problem i face is the latest image of BBB, it is not stable so sometimes i need to unplug the wifi module and then plug it again to keep it awaking. but its very rare.

**Comment by mikeshams** [comment]
****The** counter should do decrement if we pick up letters**
