### ISSUE TITLE
Display interfacing with beagle bone black, writing codes for it.

### ISSUE THREAD

**Issue by mikeshams** [Surjeet-1995/capstone-project-summer-2020#4]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of 7-segment display to a BBB in terms of Hardware and software?

**Comment by BINDU345** [comment]
Intiating display was a tough task because it is not possible to just give power supply and turn on the i2c display, we first need to intiate the gpio pin and set the i2c bus to detect the data on bus. After that we need the libraries for ht16k33  display, most of them were for python and arduino.

Also we first need to look at the manufacturer datasheet to understand charmap values. Some manufacturers have different hexadecinal values so it is important to make sure and understand the values first
