### ISSUE TITLE
Interfacing GSM module with beagle bone and preparing C codes for it

### ISSUE THREAD

**Issue by mikeshams** [Surjeet-1995/capstone-project-summer-2020#5]

**Comment by mikeshams** [comment]
1. What issues did you or others might face when connecting a GSM Module to the BBB in terms of hardware and software?
2. How did you resolve them?

**Comment by Surjeet-1995** [comment]
answer 1: interfacing gsm module with beagle bone using c language is a challanging part for me. the uart ports of bbb p9_11 and p9_13 must be enable and tested before writing the psuedo code of gsm module . the communication of beagle bone uart port is bit laggy in my bbb board. it doesn't send and receive data in same period of time. the other fix for this problem is to use aduino as slave to do transmission of data in between gsm module and bbb. it works like a library which intiate the gsm module for beagle bone and transfer the data from beagle bone to arduino. in term of hardware the some connection must be taken into care. the gsm module will not work without external power source because while sending the sms it require a good amount of current to send msg and at this time if external power source is not applied it might shutdown because of the lack of energy. Also for ignoring the this issue it is recommended to use 5v power adaptor , external battery at same time.

answer 2: fro this is used the arduino nano in between the gsm module and beagle bone. this arduino works as slave it receive the data from beagle bone and send it to gsm module. the other solution for this might be to use python libraries or other micrcontroller in circuit as the uart of beagle bone black is not responding accordingly.but i used the arduino nano in this circuit.

**Comment by mikeshams** [comment]
demonstrate the message on the cell phone when removing a letter properly
