### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by mikeshams** [Surjeet-1995/capstone-project-summer-2020#6]

**Comment by mikeshams** [comment]
1.	What are the two ways to create the PCB layout with Easy EDA?
2.	What are the limitations with each of them?

**Comment by BINDU345** [comment]
answer 1 - the first way is to create a schematics of circuit on schematics sheet, because most of the components have footprints of pcb components on sch library as well. so we can create schematics and convert that schematics into pcb design using pcb tool.
the other way is to go to the new file salect pcb sheet and drag and drop the components from library to the sheet. in this method (manually method) we have no need to arrange the components in sheet we can place as per we want. but in this we have to make connection manually on every layer

**Comment by BINDU345** [comment]
answer 2 - the limitation of converting schematics into pcb design is that we have to arrange the connection as per our requirement, also it do connection mostly on bottom layer so we have to track some on top layer as well. but its very rare, in my project it does the almost all connections.also it automatically connect the pads with pin number so you have no need assign them manually.

the limitation of creating pcb layout is that we have to do connection on every layer by ourself. its good for practice but we can also trust on easyEda tool for this. so first you need to do connection on top layer by using track and then same on bottom layer.also you may need to assign the pads by yourself.
